### ISSUE TITLE
Door crashing game

### ISSUE THREAD

**Issue by Cor1t** [Cubed-Development/Modern-Warfare-Cubed#15]
## Describe the bug

When you look at door with weapon, game crash.

## Reproducibility
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox, replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.

- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. In mw.cfg set "enableAmmoCounter" to false
2. Create new world
3. Take weapon
4. Select weapon at door

## Screenshots or/and videos

https://streamable.com/tcmc9e

## Logs or/and crash reports
https://mclo.gs/kKUlTQe

## Versions

- Modern Warfare Cubed: paneedah-modern-warfare-0.1-Dev-5
- Forge: 1.12.2 - 14.23.5.2859
- Java Version: 1.8.0_51, Oracle Corporation
- Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

## Specification:

- OS: Windows 10
- CPU: AMD ryzen 5 PRO 4650G
- GPU: NVIDIA GeForce RTX 3060 Ti
- RAM Allocated: 5GB

**Comment by Paneedah** [comment]
This issue would also be related to your severely outdated Java version.

Please update Java here: https://adoptium.net/en-gb/temurin/releases/?version=8

**Comment by JustDesoroxxx** [comment]
Please test this again after updating Java

**Comment by JustDesoroxxx** [comment]
Please test this again after updating Java.

It appear you might be using the Curse Forge launcher if so follow these instruction to change the Java that Curse Forge launcher uses once newer Java installed https://youtu.be/EGUsEq6HOd0?t=25

**Comment by Paneedah** [comment]
I believe this issue was already addressed previously. Please test again using Dev-10.

**Comment by Desoroxxx** [comment]
> Nevermind, this issue was found and addressed for the 0.1-Dev11 version.

Correction, a safe guard as been put in place for the issue not to happen, the issue is sadly not fixed yet.
It will be in the future though
